In [6]:
import json
import os
from pathlib import Path
from collections import Counter
import pandas as pd

json_dir = Path("addmypet")

entity_counter = Counter()
species_count = 0
parse_errors = []

for json_file in sorted(json_dir.glob("*.json")):
    try:
        with open(json_file, "r", encoding="utf-8") as f:
            raw = f.read().replace(": NaN", ": null").replace(":NaN", ":null")
            record = json.loads(raw)
        species_count += 1
        for entry in record.get("data", []):
            if isinstance(entry, dict) and "entity" in entry:
                entity_counter[entry["entity"]] += 1
    except Exception as e:
        parse_errors.append((json_file.name, str(e)))

print(f"Species files processed : {species_count}")
print(f"Unique entities found   : {len(entity_counter)}")
print(f"Total entity occurrences: {sum(entity_counter.values())}")
if parse_errors:
    print(f"\nFiles with parse errors ({len(parse_errors)}):")
    for fname, err in parse_errors:
        print(f"  {fname}: {err}")

df_entities = pd.DataFrame(entity_counter.most_common(), columns=["entity", "occurrences"])

pd.set_option("display.max_rows", None)
print("\nEntity statistics (sorted by occurrence):")
display(df_entities)

Species files processed : 7281
Unique entities found   : 705
Total entity occurrences: 61173

Entity statistics (sorted by occurrence):

             entity  occurrences
0                am         7221
1               Wwi         6652
2                Ri         6079
3               Wwb         5955
4                Li         4315
5                ab         4089
6                tp         3950
7                Lp         3915
8                tx         2940
9               Wwp         2415
10               tR         1746
11             Wwim         1469
12               Lb         1275
13              JOi         1215
14               tg         1202
15              Ww0         1028
16              Lim          698
17              GSI          532
18              Wwx          520
19              Lpm          469
20              tpm          406
21               Lj          331
22               tj          246
23               ap          228
24              Wdi          187
25               Ni          145
26              Wwj           92
27             Wwpm           90
28               ah           82
29              Wdb           75
30               Lh           68
31              Wdp           62
32               aj           43
33              Wdj           31
34             JOi1           30
35              Wd0           28
36               E0           23
37               NR           22
38             Li_m           21
39             Wwbm           19
40              Lbm           18
41               L0           17
42               Lx           17
43               pL           16
44            ab_f1           16
45            ab_f2           16
46               te           14
47             Lp_m           14
48               L2           13
49              Wwh           12
50               L1           12
51               tb           12
52            ab_15           11
53               L3           11
54             Li_f           10
55             Lp_f           10
56               t1           10
57               t2           10
58               t3           10
59              Ljb            9
60              amm            9
61              dLb            9
62              Wwe            8
63            ab_25            8
64            ab_20            8
65            Wwi_m            8
66               t4            8
67              Ww1            7
68               RL            7
69              Ww2            7
70             ab25            7
71             ab20            7
72             tp_m            6
73              Wde            6
74             Wwxm            6
75               L4            6
76              Wdh            6
77              apm            6
78            ab_18            6
79              pXm            5
80               V0            5
81               t5            5
82              R20            5
83             am_m            5
84             ab15            5
85             ab30            5
86               ts            4
87               Le            4
88               L5            4
89               Ej            4
90               R7            4
91              WC0            4
92              N18            4
93              Ww3            4
94               sM            4
95              tRm            4
96              WCi            4
97              WCp            4
98              dLj            4
99             ab33            4
100              Eb            4
101            Wwjm            4
102            ab10            4
103            ap_m            4
104           Wwi_f            4
105           JO_74            4
106          Wdb_f1            4
107          Wdb_f2            4
108              L6            3
109             L18            3
110            L365            3
111           ab_10            3
112              Vb            3
113             WwL            3
114             N26            3
115             Ww4            3
116             Ww5            3
117             JXL            3
118           Ri_25            3
119           tp_25            3
120             JXi            3
121           Wwi_1            3
122             WCb            3
123             R13            3
124             R18            3
125              rB            3
126           tj_15            3
127              L9            3
128             JXm            3
129              Eh            3
130           ah_15            3
131           ab_22            3
132             WwR            3
133            Ww60            3
134             R45            3
135            Ni10            3
136            Ni15            3
137            Ni20            3
138            am10            3
139            am20            3
140            tp10            3
141            tp15            3
142            tp20            3
143            Ww42            3
144           Wwp_m            3
145              R5            3
146             Ww6            2
147            ab12            2
148             L2m            2
149             LN2            2
150             LN3            2
151             LN4            2
152             Wd6            2
153           Ri_20            2
154           am_25            2
155           tp_20            2
156             JCi            2
157             N10            2
158           Wwp_1            2
159           tj_25            2
160             L20            2
161            dWwb            2
162             Wd2            2
163             Wd3            2
164             Wd4            2
165             Wd5            2
166             dLp            2
167            Ri_1            2
168         Ww_asym            2
169              L8            2
170             Wd1            2
171             Wd8            2
172              t6            2
173             L30            2
174            ah_5            2
175         Lb_asex            2
176          Lb_sex            2
177         Li_asex            2
178         Lp_asex            2
179         Ri_asex            2
180             dWw            2
181            ab28            2
182           tj_20            2
183            ah10            2
184            Ri20            2
185            Ri25            2
186             R26            2
187            ap_f            2
188            R132            2
189              Vi            2
190             R33            2
191            am15            2
192            ab_5            2
193             R68            2
194            L240            2
195             R16            2
196              pX            2
197              JO            2
198              wR            2
199            R290            2
200            Ww30            2
201              jO            2
202            Ww55            2
203             sgr            2
204           tp_15            2
205              R9            2
206              R4            2
207              R6            2
208              RQ            2
209             Lp2            2
210           ab_30            2
211             R14            2
212             R22            2
213           Wwp_f            2
214           ab_27            2
215            am11            2
216             Ww7            1
217            R135            1
218            R170            1
219           Ww290            1
220            ab18            1
221            ah14            1
222            ah17            1
223            ah24            1
224        L28_f_d1            1
225        L28_f_d2            1
226        L28_f_d3            1
227        L28_f_d4            1
228        L28_m_d1            1
229        L28_m_d2            1
230        L28_m_d3            1
231        L28_m_d4            1
232          N28_d2            1
233          N29_f1            1
234          N29_f2            1
235          N29_f3            1
236          N29_f4            1
237       Wd28_f_d1            1
238       Wd28_f_d2            1
239       Wd28_f_d3            1
240       Wd28_f_d4            1
241       Wd28_m_d1            1
242       Wd28_m_d2            1
243       Wd28_m_d3            1
244       Wd28_m_d4            1
245       Ww28_f_d1            1
246       Ww28_m_d1            1
247          ab_T16            1
248          ab_T20            1
249          ab_T21            1
250          ab_T29            1
251            ab06            1
252            ab11            1
253            Ww47            1
254            R125            1
255           Ww136            1
256            Ww_L            1
257             JCe            1
258            N24h            1
259             Nih            1
260            Wdj2            1
261              ae            1
262             Ltr            1
263             TLi            1
264             TLp            1
265           ap_13            1
266          atr_10            1
267            Wdim            1
268             Lhc            1
269             Lpc            1
270             L2b            1
271             L2i            1
272             L2p            1
273             L1t            1
274             L3t            1
275             Lht            1
276             R65            1
277             WN0            1
278             WdS            1
279            Wwe5            1
280            Wwj5            1
281            Wwjs            1
282             tgm            1
283             txm            1
284           am_20            1
285               K            1
286           aj_22            1
287           aj_30            1
288             N22            1
289             N25            1
290             N27            1
291           tp_12            1
292           tp_21            1
293           Wwi_3            1
294           Wwp_3            1
295            WwiB            1
296           WwiCS            1
297           WwiCT            1
298            WwiE            1
299            WwiG            1
300            WwiI            1
301            WwiL            1
302            WwiM            1
303            WwiN            1
304            WwiP            1
305            WwiS            1
306           WwiSB            1
307             tpB            1
308            tpCS            1
309            tpCT            1
310             tpE            1
311             tpG            1
312             tpI            1
313             tpL            1
314             tpM            1
315             tpN            1
316             tpP            1
317             tpS            1
318            tpSB            1
319           tj_12            1
320          Li_CCL            1
321          Li_SCL            1
322          Lp_CCL            1
323          Lp_SCL            1
324            Ri35            1
325            Ri45            1
326            Ri56            1
327            Ri15            1
328            Ww15            1
329             R53            1
330          Li_ref            1
331            L274            1
332           Ww122            1
333            Ww61            1
334            Ww22            1
335           tj_f1            1
336           tj_f2            1
337           tj_f3            1
338          tj_fB1            1
339          tj_fB2            1
340          tj_fB3            1
341          tj_fB4            1
342             WdR            1
343            Ri_2            1
344            Ri_3            1
345            Ri_4            1
346            Ri_5            1
347           Wwe_1            1
348           Wwe_2            1
349           Wwi_2            1
350           Wwj_1            1
351       Wwj_aphid            1
352  Wwj_artificial            1
353    Wwj_whitefly            1
354           te_23            1
355             tei            1
356            teia            1
357          tep_23            1
358           tj_23            1
359          tj_25a            1
360          tje_23            1
361          tje_25            1
362             JX5            1
363             JX6            1
364             JX7            1
365             JX8            1
366             JX9            1
367              L7            1
368             Lh1            1
369             Lh2            1
370             Lh3            1
371             Lh4            1
372             Lh5            1
373             Lh6            1
374             Lh7            1
375             Lh8            1
376             Lh9            1
377            Lj_m            1
378            Lj_w            1
379           N_HFT            1
380           N_LFT            1
381           N_MFT            1
382             Wd7            1
383             Wd9            1
384           Wwj_m            1
385              t7            1
386              t8            1
387              t9            1
388            tj_c            1
389            tp_c            1
390             tpj            1
391             L1e            1
392          L1e_14            1
393         L1e_14a            1
394          L1e_24            1
395             L2e            1
396          L2e_14            1
397         L2e_14a            1
398          L2e_24            1
399            Ww01            1
400            Ww12            1
401            Ww23            1
402            Ww34            1
403         Wwe2_25            1
404          Wwe_14            1
405          Wwe_21            1
406          Wwe_23            1
407          Wwe_24            1
408          Wwe_25            1
409            Wwj2            1
410             pA1            1
411             pA2            1
412             pA3            1
413             pA4            1
414             pAe            1
415          t01_23            1
416          t01_24            1
417          t01_25            1
418          t01_28            1
419          t12_23            1
420          t12_24            1
421          t12_25            1
422          t12_28            1
423          t23_23            1
424          t23_24            1
425          t23_25            1
426          t23_28            1
427          t34_23            1
428          t34_24            1
429          t34_25            1
430          t34_28            1
431          tbj_25            1
432          tei_24            1
433          tei_28            1
434            Ww14            1
435            Ww67            1
436             L15            1
437           ah_10            1
438             WCx            1
439              ax            1
440             Li0            1
441             Lp0            1
442             Ni0            1
443             ab0            1
444             am0            1
445             tp0            1
446            Wd37            1
447           Lb_DW            1
448          Li_DWf            1
449          Lp_DWf            1
450          Lp_DWm            1
451            L3_1            1
452            L3_2            1
453            L3_3            1
454           Ww365            1
455           Ww3_1            1
456           Ww3_2            1
457           Ww3_3            1
458             pAm            1
459           ab_28            1
460             LN5            1
461            LN52            1
462           ah_17            1
463           tb_16            1
464           tb_19            1
465          Lp_sex            1
466          Ri_sex            1
467         tp_asex            1
468            ab17            1
469            Wd55            1
470             L19            1
471             L61            1
472            L915            1
473            ab24            1
474            ab29            1
475              Fm            1
476           L1825            1
477            L730            1
478             R92            1
479            L152            1
480             WNb            1
481           ab_24            1
482            ab21            1
483            ah15            1
484            ah21            1
485           dLb10            1
486           dLb15            1
487           dLb21            1
488            ab14            1
489             JC1            1
490             JC2            1
491             JC3            1
492            JX85            1
493            Wdf1            1
494            Wdf2            1
495            Wdf3            1
496            Wwf1            1
497            Wwf2            1
498            Wwf3            1
499             L32            1
500            Ww32            1
501             L91            1
502            WwRm            1
503            Ri30            1
504           WwR20            1
505           WwR25            1
506           WwR30            1
507            tR20            1
508            tR25            1
509            tR30            1
510             Lbt            1
511             Lit            1
512             EXx            1
513            pX25            1
514           Ww118            1
515             R42            1
516             L3i            1
517           aj_18            1
518            aj_8            1
519           ap_16            1
520            p_Xm            1
521           ab_14            1
522            R195            1
523             LpC            1
524            LpmC            1
525             pXi            1
526            Lm_f            1
527            Lm_m            1
528            Lp_h            1
529              Vp            1
530             L13            1
531             L40            1
532             L72            1
533             R87            1
534             R25            1
535             R30            1
536             R35            1
537             R21            1
538             R31            1
539            R114            1
540            R142            1
541              RW            1
542            L970            1
543            ab16            1
544              JX            1
545            JO_1            1
546           JO_27            1
547          Ri_FLE            1
548            tj11            1
549            tj18            1
550              tW            1
551              pA            1
552              pP            1
553             Ww8            1
554            R277            1
555           ab_26            1
556           ab_32            1
557            L30m            1
558             L42            1
559            L42m            1
560           Ww30m            1
561           Ww42m            1
562            Ww40            1
563             ab2            1
564            aj_m            1
565             R78            1
566             Wc0            1
567            R137            1
568           Ww454            1
569           xi_WE            1
570            Ww9d            1
571            L110            1
572           tp_10            1
573             E_0            1
574             R_L            1
575             W23            1
576             R41            1
577             R59            1
578            Ww35            1
579             Wws            1
580           ab_13            1
581             Wds            1
582             Lam            1
583            Wwam            1
584             tp2            1
585              Lr            1
586             Wdr            1
587             JX0            1
588             JX1            1
589             EW4            1
590             JOw            1
591              Lo            1
592            LsWw            1
593            LtWw            1
594           ah_T1            1
595           ah_T2            1
596           ah_T3            1
597           ah_T4            1
598           ah_T5            1
599           ah_T6            1
600            ab_B            1
601            R400            1
602           k_tar            1
603            ah12            1
604            Ri_0            1

In [7]:
import json
from pathlib import Path
from collections import Counter
import pandas as pd

# ── Canonical DEB zero-variate entities ───────────────────────────────────────
CANONICAL = {
    # ages / time intervals
    'ab', 'ah', 'aj', 'am', 'ap', 'as', 'ae', 'ax', 'aR',
    'tg', 'tx', 'tR', 'ts', 'tb', 'te', 'tj', 'tp', 'tW',
    # lengths
    'L0', 'Lh', 'Lb', 'Lx', 'Ls', 'Lj', 'Lp', 'LR', 'Li',
    'Lr', 'Lo', 'Lam', 'LsWw', 'LtWw',
    'dLb', 'dLp', 'dLj',
    # volumes
    'V0', 'Vb', 'Vp', 'Vi',
    # wet weights
    'Ww0', 'Wwh', 'Wwb', 'Wwx', 'Wws', 'Wwj', 'Wwp', 'Wwe', 'Wwi',
    'WwR', 'Ww_L', 'dWw', 'dWwb',
    # dry weights
    'Wd0', 'Wdh', 'Wdb', 'Wdx', 'Wds', 'Wdj', 'Wdp', 'Wde', 'Wdi', 'Wdr',
    'WdR',
    # carbon / nitrogen content
    'WC0', 'WCb', 'WCi', 'WCp', 'WCx', 'WN0', 'WNb',
    # energy
    'E0', 'Eb', 'Eh', 'Ej', 'EXx', 'EL',
    # rates / reproduction
    'Ri', 'rB', 'GSI', 'Ni',
    # feeding / respiration
    'Fm', 'K', 'KV',
    'JOi', 'JO', 'JOw',
    'JX', 'JXi', 'JXm', 'JX_L',
    'JCi',
    'pAm', 'pXi', 'pXm', 'pL', 'pP', 'pA',
    # other scalars
    'sM', 'sgr', 'xi_WE', 'RQ', 'NR',
    'del_S', 'del_Lip',
    'k_tar',
}

# Sort by length descending so the longest canonical prefix wins
CANONICAL_SORTED = sorted(CANONICAL, key=len, reverse=True)

# ── MANUAL: cases that cannot be resolved by prefix matching ──────────────────
MANUAL = {
    # JC prefix not in CANONICAL — map to JCi
    'JC1': 'JCi', 'JC2': 'JCi', 'JC3': 'JCi', 'JCe': 'JCi', 'JC_p': 'JCi',
    # pX not in CANONICAL — map to pXi
    'pX': 'pXi', 'pX25': 'pXi',
    # p_Xm: underscore is a prefix not suffix — map to pXm
    'p_Xm': 'pXm',
    # NR is in CANONICAL but biologically maps to Ni
    'NR': 'Ni',
    # case change: lowercase c → uppercase C
    'Wc0': 'WC0',
}


def to_canonical(raw):
    """Return the canonical entity name, or None if unmappable."""
    raw = raw.strip()
    if raw in CANONICAL:
        return raw
    if raw in MANUAL:
        return MANUAL[raw]
    for c in CANONICAL_SORTED:
        if raw.startswith(c):
            return c
    return None


# ── Step 1: count occurrences by canonical entity ─────────────────────────────
json_dir = Path("addmypet")

canon_counter = Counter()
unmapped      = Counter()

for json_file in sorted(json_dir.glob("*.json")):
    try:
        with open(json_file, "r", encoding="utf-8") as f:
            raw = f.read().replace(": NaN", ": null").replace(":NaN", ":null")
            record = json.loads(raw)
        for entry in record.get("data", []):
            if isinstance(entry, dict) and "entity" in entry:
                e = entry["entity"]
                c = to_canonical(e)
                if c:
                    canon_counter[c] += 1
                else:
                    unmapped[e] += 1
    except Exception as ex:
        print(f"Parse error in {json_file.name}: {ex}")

# ── Step 2: statistics ────────────────────────────────────────────────────────
df_canon = pd.DataFrame(canon_counter.most_common(), columns=["CANONICAL", "occurrences"])
print(f"Canonical entities : {len(df_canon)}")
print(f"Total occurrences  : {df_canon['occurrences'].sum()}")
if unmapped:
    print(f"\nNot mapped — {len(unmapped)} labels, {sum(unmapped.values())} occurrences:")
    for e, cnt in unmapped.most_common():
        print(f"  {e:30s}  {cnt}")

pd.set_option("display.max_rows", None)
print("\nCanonical entity statistics:")
display(df_canon)

# ── Step 3: rewrite JSON files with canonical entity names ───────────────────
updated_files = 0
total_files   = len(list(json_dir.glob("*.json")))

for json_file in sorted(json_dir.glob("*.json")):
    try:
        with open(json_file, "r", encoding="utf-8") as f:
            raw_text = f.read().replace(": NaN", ": null").replace(":NaN", ":null")
            record = json.loads(raw_text)
    except Exception as ex:
        print(f"Skipping {json_file.name}: {ex}")
        continue

    changed = False
    for entry in record.get("data", []):
        if isinstance(entry, dict) and "entity" in entry:
            c = to_canonical(entry["entity"])
            if c and c != entry["entity"]:
                entry["entity"] = c
                changed = True

    if changed:
        with open(json_file, "w", encoding="utf-8") as f:
            json.dump(record, f, indent=2, ensure_ascii=False)
        updated_files += 1

print(f"\nJSON files updated: {updated_files} / {total_files}")

Canonical entities : 99
Total occurrences  : 60752

Not mapped — 246 labels, 421 occurrences:
  L2                              13
  L1                              12
  L3                              11
  t1                              10
  t2                              10
  t3                              10
  t4                              8
  Ww1                             7
  RL                              7
  Ww2                             7
  L4                              6
  t5                              5
  R20                             5
  Le                              4
  L5                              4
  R7                              4
  N18                             4
  Ww3                             4
  L6                              3
  L18                             3
  L365                            3
  WwL                             3
  N26                             3
  Ww4                             3
  Ww5                             3
  R13                             3
  R18                             3
  L9                              3
  Ww60                            3
  R45                             3
  Ww42                            3
  R5                              3
  Ww6                             2
  L2m                             2
  LN2                             2
  LN3                             2
  LN4                             2
  Wd6                             2
  N10                             2
  L20                             2
  Wd2                             2
  Wd3                             2
  Wd4                             2
  Wd5                             2
  Ww_asym                         2
  L8                              2
  Wd1                             2
  Wd8                             2
  t6                              2
  L30                             2
  R26                             2
  R132                            2
  R33                             2
  R68                             2
  L240                            2
  R16                             2
  wR                              2
  R290                            2
  Ww30                            2
  jO                              2
  Ww55                            2
  R9                              2
  R4                              2
  R6                              2
  R14                             2
  R22                             2
  Ww7                             1
  R135                            1
  R170                            1
  Ww290                           1
  L28_f_d1                        1
  L28_f_d2                        1
  L28_f_d3                        1
  L28_f_d4                        1
  L28_m_d1                        1
  L28_m_d2                        1
  L28_m_d3                        1
  L28_m_d4                        1
  N28_d2                          1
  N29_f1                          1
  N29_f2                          1
  N29_f3                          1
  N29_f4                          1
  Wd28_f_d1                       1
  Wd28_f_d2                       1
  Wd28_f_d3                       1
  Wd28_f_d4                       1
  Wd28_m_d1                       1
  Wd28_m_d2                       1
  Wd28_m_d3                       1
  Wd28_m_d4                       1
  Ww28_f_d1                       1
  Ww28_m_d1                       1
  Ww47                            1
  R125                            1
  Ww136                           1
  N24h                            1
  Ltr                             1
  TLi                             1
  TLp                             1
  atr_10                          1
  L2b                             1
  L2i                             1
  L2p                             1
  L1t                             1
  L3t                             1
  R65                             1
  WdS                             1
  N22                             1
  N25                             1
  N27                             1
  Ww15                            1
  R53                             1
  L274                            1
  Ww122                           1
  Ww61                            1
  Ww22                            1
  L7                              1
  N_HFT                           1
  N_LFT                           1
  N_MFT                           1
  Wd7                             1
  Wd9                             1
  t7                              1
  t8                              1
  t9                              1
  L1e                             1
  L1e_14                          1
  L1e_14a                         1
  L1e_24                          1
  L2e                             1
  L2e_14                          1
  L2e_14a                         1
  L2e_24                          1
  Ww12                            1
  Ww23                            1
  Ww34                            1
  t01_23                          1
  t01_24                          1
  t01_25                          1
  t01_28                          1
  t12_23                          1
  t12_24                          1
  t12_25                          1
  t12_28                          1
  t23_23                          1
  t23_24                          1
  t23_25                          1
  t23_28                          1
  t34_23                          1
  t34_24                          1
  t34_25                          1
  t34_28                          1
  Ww14                            1
  Ww67                            1
  L15                             1
  Wd37                            1
  L3_1                            1
  L3_2                            1
  L3_3                            1
  Ww365                           1
  Ww3_1                           1
  Ww3_2                           1
  Ww3_3                           1
  LN5                             1
  LN52                            1
  Wd55                            1
  L19                             1
  L61                             1
  L915                            1
  L1825                           1
  L730                            1
  R92                             1
  L152                            1
  Wdf1                            1
  Wdf2                            1
  Wdf3                            1
  Wwf1                            1
  Wwf2                            1
  Wwf3                            1
  L32                             1
  Ww32                            1
  L91                             1
  Ww118                           1
  R42                             1
  L3i                             1
  R195                            1
  Lm_f                            1
  Lm_m                            1
  L13                             1
  L40                             1
  L72                             1
  R87                             1
  R25                             1
  R30                             1
  R35                             1
  R21                             1
  R31                             1
  R114                            1
  R142                            1
  RW                              1
  L970                            1
  Ww8                             1
  R277                            1
  L30m                            1
  L42                             1
  L42m                            1
  Ww30m                           1
  Ww42m                           1
  Ww40                            1
  R78                             1
  R137                            1
  Ww454                           1
  Ww9d                            1
  L110                            1
  E_0                             1
  R_L                             1
  W23                             1
  R41                             1
  R59                             1
  Ww35                            1
  Wwam                            1
  EW4                             1
  R400                            1
  L_24                            1
  LCi                             1
  R50                             1
  Ww1150                          1
  L76                             1
  Ww160                           1
  R97                             1
  tTj_10                          1
  tTj_6                           1
  L1_f                            1
  L1_m                            1
  L300                            1
  Ww300                           1
  L10                             1
  L17                             1
  Ww115                           1
  R097                            1
  N1                              1
  N7                              1
  Wwm41                           1
  Ww13                            1
  Ww33                            1

Canonical entity statistics:

   CANONICAL  occurrences
0        Wwi         8155
1         am         7255
2         Ri         6107
3        Wwb         5977
4         Li         5058
5         Lp         4426
6         tp         4404
7         ab         4232
8         tx         2941
9        Wwp         2516
10        tR         1753
11        Lb         1302
12       JOi         1245
13        tg         1203
14       Ww0         1029
15       GSI          532
16       Wwx          526
17        Lj          344
18        tj          268
19        ap          244
20       Wdi          188
21        Ni          156
22        ah          109
23       Wwj          104
24       Wdb           83
25        Lh           79
26       Wdp           62
27        aj           49
28       Wdj           32
29       Wd0           28
30        E0           23
31        NR           22
32        te           21
33       Wwe           17
34        L0           17
35        Lx           17
36        pL           16
37        tb           15
38       dLb           13
39       Wwh           12
40        JX           12
41        JO            8
42       WwR            7
43       pXm            6
44       JCi            6
45       Wde            6
46        pA            6
47       Wdh            6
48        Vb            5
49        V0            5
50       WC0            5
51        rB            5
52       JXm            5
53        ts            4
54        Ej            4
55        sM            4
56       WCi            4
57       WCp            4
58       dLj            4
59       WdR            4
60        Eb            4
61       pXi            4
62        Vi            4
63       JXi            3
64       WCb            3
65        Eh            3
66        Vp            3
67      dWwb            2
68       dLp            2
69       pAm            2
70       dWw            2
71       sgr            2
72        RQ            2
73      Ww_L            1
74        ae            1
75       WN0            1
76         K            1
77       WCx            1
78        ax            1
79        Fm            1
80       WNb            1
81       EXx            1
82        tW            1
83        pP            1
84     xi_WE            1
85       Wws            1
86       Wds            1
87       Lam            1
88        Lr            1
89       Wdr            1
90       JOw            1
91        Lo            1
92      LsWw            1
93      LtWw            1
94     k_tar            1
95     del_S            1
96        LR            1
97      JX_L            1
98   del_Lip            1

JSON files updated: 2223 / 7281

In [8]:
import json
import os
from pathlib import Path
from collections import Counter
import pandas as pd

json_dir = Path("addmypet")

entity_counter = Counter()
species_count = 0
parse_errors = []

for json_file in sorted(json_dir.glob("*.json")):
    try:
        with open(json_file, "r", encoding="utf-8") as f:
            raw = f.read().replace(": NaN", ": null").replace(":NaN", ":null")
            record = json.loads(raw)
        species_count += 1
        for entry in record.get("data", []):
            if isinstance(entry, dict) and "entity" in entry:
                entity_counter[entry["entity"]] += 1
    except Exception as e:
        parse_errors.append((json_file.name, str(e)))

print(f"Species files processed : {species_count}")
print(f"Unique entities found   : {len(entity_counter)}")
print(f"Total entity occurrences: {sum(entity_counter.values())}")
if parse_errors:
    print(f"\nFiles with parse errors ({len(parse_errors)}):")
    for fname, err in parse_errors:
        print(f"  {fname}: {err}")

df_entities = pd.DataFrame(entity_counter.most_common(), columns=["entity", "occurrences"])

pd.set_option("display.max_rows", None)
print("\nEntity statistics (sorted by occurrence):")
display(df_entities)

Species files processed : 7281
Unique entities found   : 345
Total entity occurrences: 61173

Entity statistics (sorted by occurrence):

        entity  occurrences
0          Wwi         8155
1           am         7255
2           Ri         6107
3          Wwb         5977
4           Li         5058
5           Lp         4426
6           tp         4404
7           ab         4232
8           tx         2941
9          Wwp         2516
10          tR         1753
11          Lb         1302
12         JOi         1245
13          tg         1203
14         Ww0         1029
15         GSI          532
16         Wwx          526
17          Lj          344
18          tj          268
19          ap          244
20         Wdi          188
21          Ni          156
22          ah          109
23         Wwj          104
24         Wdb           83
25          Lh           79
26         Wdp           62
27          aj           49
28         Wdj           32
29         Wd0           28
30          E0           23
31          NR           22
32          te           21
33         Wwe           17
34          L0           17
35          Lx           17
36          pL           16
37          tb           15
38          L2           13
39         dLb           13
40         Wwh           12
41          L1           12
42          JX           12
43          L3           11
44          t1           10
45          t2           10
46          t3           10
47          t4            8
48          JO            8
49         Ww1            7
50          RL            7
51         Ww2            7
52         WwR            7
53         pXm            6
54         JCi            6
55         Wde            6
56          L4            6
57          pA            6
58         Wdh            6
59          Vb            5
60          V0            5
61         WC0            5
62          t5            5
63          rB            5
64         JXm            5
65         R20            5
66          ts            4
67          Le            4
68          L5            4
69          Ej            4
70          R7            4
71         N18            4
72         Ww3            4
73          sM            4
74         WCi            4
75         WCp            4
76         dLj            4
77         WdR            4
78          Eb            4
79         pXi            4
80          Vi            4
81          L6            3
82         L18            3
83        L365            3
84         WwL            3
85         N26            3
86         Ww4            3
87         Ww5            3
88         JXi            3
89         WCb            3
90         R13            3
91         R18            3
92          L9            3
93          Eh            3
94        Ww60            3
95         R45            3
96          Vp            3
97        Ww42            3
98          R5            3
99         Ww6            2
100        L2m            2
101        LN2            2
102        LN3            2
103        LN4            2
104        Wd6            2
105        N10            2
106        L20            2
107       dWwb            2
108        Wd2            2
109        Wd3            2
110        Wd4            2
111        Wd5            2
112        dLp            2
113    Ww_asym            2
114         L8            2
115        Wd1            2
116        Wd8            2
117         t6            2
118        L30            2
119        pAm            2
120        dWw            2
121        R26            2
122       R132            2
123        R33            2
124        R68            2
125       L240            2
126        R16            2
127         wR            2
128       R290            2
129       Ww30            2
130         jO            2
131       Ww55            2
132        sgr            2
133         R9            2
134         R4            2
135         R6            2
136         RQ            2
137        R14            2
138        R22            2
139        Ww7            1
140       R135            1
141       R170            1
142      Ww290            1
143   L28_f_d1            1
144   L28_f_d2            1
145   L28_f_d3            1
146   L28_f_d4            1
147   L28_m_d1            1
148   L28_m_d2            1
149   L28_m_d3            1
150   L28_m_d4            1
151     N28_d2            1
152     N29_f1            1
153     N29_f2            1
154     N29_f3            1
155     N29_f4            1
156  Wd28_f_d1            1
157  Wd28_f_d2            1
158  Wd28_f_d3            1
159  Wd28_f_d4            1
160  Wd28_m_d1            1
161  Wd28_m_d2            1
162  Wd28_m_d3            1
163  Wd28_m_d4            1
164  Ww28_f_d1            1
165  Ww28_m_d1            1
166       Ww47            1
167       R125            1
168      Ww136            1
169       Ww_L            1
170       N24h            1
171         ae            1
172        Ltr            1
173        TLi            1
174        TLp            1
175     atr_10            1
176        L2b            1
177        L2i            1
178        L2p            1
179        L1t            1
180        L3t            1
181        R65            1
182        WN0            1
183        WdS            1
184          K            1
185        N22            1
186        N25            1
187        N27            1
188       Ww15            1
189        R53            1
190       L274            1
191      Ww122            1
192       Ww61            1
193       Ww22            1
194         L7            1
195      N_HFT            1
196      N_LFT            1
197      N_MFT            1
198        Wd7            1
199        Wd9            1
200         t7            1
201         t8            1
202         t9            1
203        L1e            1
204     L1e_14            1
205    L1e_14a            1
206     L1e_24            1
207        L2e            1
208     L2e_14            1
209    L2e_14a            1
210     L2e_24            1
211       Ww12            1
212       Ww23            1
213       Ww34            1
214     t01_23            1
215     t01_24            1
216     t01_25            1
217     t01_28            1
218     t12_23            1
219     t12_24            1
220     t12_25            1
221     t12_28            1
222     t23_23            1
223     t23_24            1
224     t23_25            1
225     t23_28            1
226     t34_23            1
227     t34_24            1
228     t34_25            1
229     t34_28            1
230       Ww14            1
231       Ww67            1
232        L15            1
233        WCx            1
234         ax            1
235       Wd37            1
236       L3_1            1
237       L3_2            1
238       L3_3            1
239      Ww365            1
240      Ww3_1            1
241      Ww3_2            1
242      Ww3_3            1
243        LN5            1
244       LN52            1
245       Wd55            1
246        L19            1
247        L61            1
248       L915            1
249         Fm            1
250      L1825            1
251       L730            1
252        R92            1
253       L152            1
254        WNb            1
255       Wdf1            1
256       Wdf2            1
257       Wdf3            1
258       Wwf1            1
259       Wwf2            1
260       Wwf3            1
261        L32            1
262       Ww32            1
263        L91            1
264        EXx            1
265      Ww118            1
266        R42            1
267        L3i            1
268       R195            1
269       Lm_f            1
270       Lm_m            1
271        L13            1
272        L40            1
273        L72            1
274        R87            1
275        R25            1
276        R30            1
277        R35            1
278        R21            1
279        R31            1
280       R114            1
281       R142            1
282         RW            1
283       L970            1
284         tW            1
285         pP            1
286        Ww8            1
287       R277            1
288       L30m            1
289        L42            1
290       L42m            1
291      Ww30m            1
292      Ww42m            1
293       Ww40            1
294        R78            1
295       R137            1
296      Ww454            1
297      xi_WE            1
298       Ww9d            1
299       L110            1
300        E_0            1
301        R_L            1
302        W23            1
303        R41            1
304        R59            1
305       Ww35            1
306        Wws            1
307        Wds            1
308        Lam            1
309       Wwam            1
310         Lr            1
311        Wdr            1
312        EW4            1
313        JOw            1
314         Lo            1
315       LsWw            1
316       LtWw            1
317       R400            1
318      k_tar            1
319      del_S            1
320       L_24            1
321        LCi            1
322         LR            1
323        R50            1
324     Ww1150            1
325        L76            1
326      Ww160            1
327        R97            1
328     tTj_10            1
329      tTj_6            1
330       JX_L            1
331       L1_f            1
332       L1_m            1
333    del_Lip            1
334       L300            1
335      Ww300            1
336        L10            1
337        L17            1
338      Ww115            1
339       R097            1
340         N1            1
341         N7            1
342      Wwm41            1
343       Ww13            1
344       Ww33            1